# Change the prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable the mouse
set -g mouse on

# Use pretty colors
set -a terminal-features 'xterm-ghostty:RGB'

# Play nice with Vim
set -g escape-time 10
set -g focus-events on
