# Rebind prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Set default $TERM
set -g default-terminal "tmux-256color"

# Enable mouse
set -g mouse on

# Set window options
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Set options for Vim
set -g escape-time 10
set -g focus-events on
