# Change the prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Make tmux more pleasant
set -g mouse on
set -g default-terminal 'tmux-256color'

# Play nice with Vim
set -g escape-time 10
set -g focus-events on
